Repository LiveforTomorrow/helpline-web, pull requests merged in 2020-04, with the labels that each got.

#2 add comprehesive unit tests
  jest.config.js
  package-lock.json
  package.json
  src/components/CountrySelect/CountrySelect.test.tsx
  src/components/CountrySelect/CountrySelect.tsx
  src/components/Placeholder/Placeholder.spec.tsx
  src/components/Placeholder/Placeholder.test.tsx
  src/components/Placeholder/Placeholder.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/components/TopBar/TopBar.test.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopicSelect/TopicSelect.test.tsx
  src/components/TopicSelect/TopicSelect.tsx
  tests/setup.ts
Labels: enhancement

#4 Footer component updates
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
Labels: enhancement, merged into stage

#5 add subdivision select
  pages/[countryCode].tsx
  pages/[countryCode]/[subdivisionCode].tsx
  pages/search.tsx
  schema.json
  src/components/CountrySelect/CountrySelect.stories.tsx
  src/components/CountrySelect/CountrySelect.test.tsx
  src/components/CountrySelect/CountrySelect.tsx
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  types/GetCountriesAndSubdivisions.ts
  types/GetCountriesAndTopics.ts
  types/GetCountry.ts
  types/GetCountryAndSubdivisions.ts
Labels: enhancement, merged into stage

#7 add link to placeholder
  src/components/Placeholder/Placeholder.tsx
Labels: enhancement, merged into stage

#9 add chromatic
  .travis.yml
  bin/travis_chromatic.sh
  package-lock.json
  package.json
  src/components/Chrome/Chrome.stories.tsx
Labels: enhancement

#10 add viewports to chromatic
  .eslintrc.js
  .github/workflows/merge-master-into-storybook.yml.yml
  .github/workflows/merge-stage-into-stage-storybook.yml
  .storybook/config.js
  src/components/Chrome/Chrome.stories.tsx
  src/components/CountrySelect/CountrySelect.stories.tsx
  src/components/Footer/Footer.stories.tsx
  src/components/Placeholder/Placeholder.stories.tsx
  src/components/Search/Search.stories.tsx
  src/components/TopBar/TopBar.stories.tsx
  src/components/TopicSelect/TopicSelect.stories.tsx
Labels: enhancement

#8 update crowdsource link
  src/components/Placeholder/Placeholder.test.tsx
  src/components/Placeholder/Placeholder.tsx
Labels: enhancement

#6 Organization card component
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  pages/[countryCode].tsx
  pages/[countryCode]/[subdivisionCode].tsx
  src/components/Chrome/Chrome.stories.tsx
  src/components/Footer/Footer.stories.tsx
  src/components/NavBar/NavBar.stories.tsx
  src/components/NavBar/NavBar.test.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/index.tsx
  src/components/OrganizationCard/OrganizationCard.stories.tsx
  src/components/OrganizationCard/OrganizationCard.test.tsx
  src/components/OrganizationCard/OrganizationCard.tsx
  src/components/OrganizationCard/index.tsx
  src/components/OrganizationList/OrganizationList.stories.tsx
  src/components/OrganizationList/OrganizationList.test.tsx
  src/components/OrganizationList/OrganizationList.tsx
  src/components/OrganizationList/index.tsx
  src/components/OrganizationOpen/OrganizationOpen.stories.tsx
  src/components/OrganizationOpen/OrganizationOpen.test.tsx
  src/components/OrganizationOpen/OrganizationOpen.tsx
  src/components/OrganizationOpen/index.tsx
  src/components/Placeholder/Placeholder.stories.tsx
  src/components/Search/Search.stories.tsx
  src/components/TopBar/TopBar.stories.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopicSelect/TopicSelect.stories.tsx
  src/components/TopicSelect/TopicSelect.tsx
  src/theme.ts
  src/util/isOpen.test.ts
  src/util/isOpen.ts
  types/GetCountry.ts
  types/GetCountryAndOrganizations.ts
  types/GetCountryAndSubdivisions.ts
  types/GetCountrySubdivisionsAndOrganizations.ts
Labels: enhancement, merged into stage

#20 organization list component
  pages/[countryCode].tsx
  pages/[countryCode]/[subdivisionCode].tsx
  src/components/OrganizationCard/OrganizationCard.stories.tsx
  src/components/OrganizationCard/OrganizationCard.test.tsx
  src/components/OrganizationCard/OrganizationCard.tsx
  src/components/OrganizationFilter/OrganizationFilter.test.tsx
  src/components/OrganizationFilter/OrganizationFilter.tsx
  src/components/OrganizationList/OrganizationList.stories.tsx
  src/components/OrganizationList/OrganizationList.test.tsx
  src/components/OrganizationList/OrganizationList.tsx
  src/components/OrganizationOpen/OrganizationOpen.stories.tsx
  src/components/OrganizationOpen/OrganizationOpen.test.tsx
  src/components/TopBar/TopBar.tsx
  src/util/filterAndSortOrganizations.test.ts
  src/util/filterAndSortOrganizations.ts
  src/util/formatArrayIntoSentence.test.ts
  src/util/formatArrayIntoSentence.ts
  src/util/isOpen.test.ts
  src/util/isOpen.ts
  types/GetCountryAndOrganizations.ts
  types/GetCountryCodeProps.ts
  types/GetCountrySubdivisionsAndOrganizations.ts
  types/GetSubdivisionCodeProps.ts
Labels: enhancement, merged into stage

#22 add sidebar
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/SideBar/SideBar.stories.tsx
  src/components/SideBar/SideBar.test.tsx
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/index.tsx
Labels: enhancement, merged into stage

#47 show only national helplines
  pages/[countryCode].tsx
Labels: bug, merged into stage

#29 [1st Merge]: Feature/organization carousel
  package-lock.json
  package.json
  pages/about.tsx
  pages/embed.tsx
  pages/organizations/[slug].tsx
  pages/widget.tsx
  pages/widget/[widgetCountyCode].tsx
  pages/widget/index.tsx
  public/bg0.jpg
  public/bg1.jpg
  src/components/About/About.stories.tsx
  src/components/About/About.test.tsx
  src/components/About/About.tsx
  src/components/About/index.tsx
  src/components/CountrySelect/CountrySelect.stories.tsx
  src/components/CountrySelect/CountrySelect.tsx
  src/components/EmbedInfo/EmbedInfo.stories.tsx
  src/components/EmbedInfo/EmbedInfo.test.tsx
  src/components/EmbedInfo/EmbedInfo.tsx
  src/components/EmbedInfo/index.tsx
  src/components/EmbedLink/EmbedLink.stories.tsx
  src/components/EmbedLink/EmbedLink.test.tsx
  src/components/EmbedLink/EmbedLink.tsx
  src/components/EmbedLink/index.tsx
  src/components/ItemSelect/ItemSelect.tsx
  src/components/OrganizationCarousel/OrganizationCarousel.stories.tsx
  src/components/OrganizationCarousel/OrganizationCarousel.test.tsx
  src/components/OrganizationCarousel/OrganizationCarousel.tsx
  src/components/OrganizationCarousel/OrganizationCarouselButtons.tsx
  src/components/OrganizationFilter/OrganizationFilter.tsx
  src/components/OrganizationItem/OrganizationItem.stories.tsx
  src/components/OrganizationItem/OrganizationItem.test.tsx
  src/components/OrganizationItem/OrganizationItem.tsx
  src/components/OrganizationItem/index.tsx
  src/components/SearchHeader/SearchHeader.stories.tsx
  src/components/SearchHeader/SearchHeader.tsx
  src/components/TopBar/TopBar.stories.tsx
  src/components/TopBar/TopBar.tsx
  src/components/Widget/Widget.stories.tsx
  src/components/Widget/Widget.test.tsx
  src/components/Widget/Widget.tsx
  src/components/Widget/index.tsx
  src/context/organizationContext.tsx
  src/context/organizationProviderMock.tsx
  src/theme.ts
  src/util/conditionalWrapper.test.tsx
  src/util/conditionalWrapper.tsx
  types/GetCountryCodesAndNames.ts
  types/GetOrganizationSlugProps.ts
  types/GetOrganizations.ts
  types/GetWidgetCountriesAndSubdivisions.ts
  types/GetWidgetCountryCodeProps.ts
Labels: merged into stage

#32 [2nd Merge]: Feature/widget component
  src/components/CountrySelect/CountrySelect.tsx
  src/components/OrganizationCarousel/OrganizationCarousel.test.tsx
  src/components/OrganizationCarousel/OrganizationCarouselButtons.tsx
  src/components/OrganizationCarousel/index.tsx
  src/components/SearchHeader/SearchHeader.tsx
Labels: merged into stage

#33 [1st Merge]: embed functionality
  src/components/EmbedInfo/EmbedInfo.tsx
  src/components/EmbedLink/EmbedLink.tsx
Labels: merged into stage

#50 add featured
  pages/[countryCode].tsx
  pages/[countryCode]/[subdivisionCode].tsx
  pages/organizations/[slug].tsx
  pages/widget/[countryCode].tsx
  pages/widget/[countryCode]/[subdivisionCode].tsx
  schema.json
  src/components/OrganizationCard/OrganizationCard.stories.tsx
  src/components/OrganizationCard/OrganizationCard.test.tsx
  src/components/OrganizationCard/OrganizationCard.tsx
  src/components/OrganizationFilter/OrganizationFilter.tsx
  src/components/OrganizationItem/OrganizationItem.test.tsx
  src/components/OrganizationItem/OrganizationItem.tsx
  src/components/OrganizationList/OrganizationList.stories.tsx
  src/components/OrganizationList/OrganizationList.tsx
  src/components/OrganizationOpen/OrganizationOpen.test.tsx
  src/components/OrganizationOpen/OrganizationOpen.tsx
  src/components/Widget/Widget.stories.tsx
  src/components/Widget/Widget.test.tsx
  src/components/WidgetOrganizationList/WidgetOrganizationList.test.tsx
  src/util/filterAndSortOrganizations.test.ts
  src/util/filterAndSortOrganizations.ts
  types/GetCountryCodeProps.ts
  types/GetCountryCodeSubdivisonCodeProps.ts
  types/GetOrganizationsSlugProps.ts
  types/GetWidgetCountryCodeProps.ts
  types/GetWidgetSubdivisionCodeProps.ts
Labels: enhancement

#51 widget
  .gitignore
  package-lock.json
  package.json
  pages/widget/[countryCode].tsx
  pages/widget/[countryCode]/[subdivisionCode].tsx
  public/widget-demo.html
  src/components/Embed/Embed.tsx
  src/widget/widget.tsx
  webpack.config.js
Labels: enhancement

#64 change to chromatic
  package-lock.json
  package.json
Labels: dependencies
